services:
  api:
    image: node:20-slim
    working_dir: /app
    container_name: cfl-back
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
    command: >
      sh -c "npm install && npm run dev"
